AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Cost Tracker API

Globals:
  Function:
    Timeout: 30
    Runtime: python3.9
    Environment:
      Variables:
        EXPENSES_TABLE: !Ref ExpensesTable
        AWS_REGION: !Ref AWS::Region

Resources:
  CostTrackerAPI:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: main.handler
      Events:
        CostTrackerAPI:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ExpensesTable

  ExpensesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: expenses-table
      AttributeDefinitions:
        - AttributeName: expense_id
          AttributeType: S
      KeySchema:
        - AttributeName: expense_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  CostTrackerApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
